<?php
    // Put this in a variable to make typing quicker.
    $d = Mage::helper('diy');
?>

body {
    font-size: <?php echo $d->getValue("global", "font_size"); ?>px;
    color: #<?php echo $d->getValue("global", "font_colour")?>;
}

a {
    color: #<?php echo $d->getValue("global", "link_colour") ?>;
}

a:hover {
    color: #<?php echo $d->getValue("global", "link_hover_colour") ?>;
}

input, select, textarea, button {
    color: #<?php echo $d->getValue("global", "input_colour") ?>;
    font-family: <?php echo $d->getValue("global", "input_font_family") ?>;
    font-size: <?php echo $d->getValue("global", "input_font_size") ?>px;
}

input.input-text, select, textarea {
    background-color: #<?php echo $d->getValue("global", "input_background_colour") ?>;
    border-colour: #<?php echo $d->getValue("global", "input_border_colour") ?>;
}

input.input-text, textarea {
    padding: <?php echo $d->getValue("global", "input_text_padding"); ?>px;
}
.header .links a {
    color: #<?php echo $d->getValue("global", "header_link_colour")?>;
}

#nav {
    background-color: #<?php echo $d->getValue("global", "nav_bar_background")?>;
}

#nav li {
    background-color: #<?php echo $d->getValue("global", "nav_item_background")?>;
}

#nav li a {
    color: #<?php echo $d->getValue("global", "nav_item_link_colour")?>;
}

#nav li.active a {
    color: #<?php echo $d->getValue("global", "nav_item_active_link_colour")?>;
}

#nav li a:hover {
    color: #<?php echo $d->getValue("global", "nav_item_link_hover_colour")?>;
}

#nav ul li a {
    background-color: #<?php echo $d->getValue("global", "nav_sub_item_background_colour")?>;
    color: #<?php echo $d->getValue("global", "nav_sub_item_link_colour")?>;
}

#nav ul li a:hover {
    background-color: #<?php echo $d->getValue("global", "nav_sub_item_background_colour")?>;
}

#nav ul, #nav div {
    <?php if ($d->getValue("global", "nav_sub_list_border" ) != 1): ?>
        border: none;
    <?php endif; ?>
    border-color: #<?php echo $d->getValue("global", "nav_sub_list_border_colour")?>;
}

<?php if ($d->getValue("catalog_category_view", "pager_border") != 1): ?>
    .pager, .sorter {
        border: none;
    }
<?php endif ?>

.pager, .sorter {
    background: #<?php echo $d->getValue("catalog_category_view", "pager_background") ?>;
}