<?php
    $d = Mage::helper('diy');
?>

body {
    font-size: <?php echo $d->getValue("global", "font_size"); ?>px;
    color: #<?php echo $d->getValue("global", "font_colour")?>;
}

a {
    color: #<?php echo $d->getValue("global", "link_colour") ?>;
}

a:hover {
    color: #<?php echo $d->getValue("global", "link_hover_colour") ?>;
}

.header .links a {
	color: #<?php echo $d->getValue("global", "header_link_colour")?>;
}

<?php if ($d->getValue("catalog_category_view", "pager_border") != 1): ?>
    .pager, .sorter {
        border: none;
    }
<?php endif ?>

.pager, .sorter {
    background: #<?php echo $d->getValue("catalog_category_view", "pager_background") ?>;
}