<?php
// {{license}}
?>
<?php
/**
 * @see Meanbee_Diy_Block_Admin_Design_Abstract
 * @author Nicholas Jones
 */
?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="diy_form" enctype="multipart/form-data">
    
    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
    <input type="hidden" name="return_url" value="<?php echo $this->getUrl("*/*/*") ?>" />
    
    <input type="hidden" id="diy_publish" name="publish" value="0" />
    
    <div class="content-header skip-header" id="content_header">
        <table cellspacing="0">
            <tr>
                <td><h3 id="content_header_text"><?php echo $this->__($this->getTitle()) ?></h3></td>
                <td class="form-buttons">
                    <button style="" onclick="" class="scalable back" type="button" id="diy_back"><span>Back</span></button>
                    <button style="" onclick="$('diy_form').submit()" class="scalable save" type="button" id="diy_save"><span>Save</span></button>
                    <button style="" onclick="$('diy_publish').value = 1; $('diy_form').submit()" class="scalable save" type="button" id="diy_save"><span>Save &amp; Publish</span></button>
                </td>
            </tr>
        </table>
    </div>

    <?php if (!$this->isDiyThemeEnabledForStore()): ?>
        <ul class="messages"><li class="notice-msg"><ul><li><span>Only the 'Layout Settings' controls are compatible with stores that are not running the DIY Mage theme.  The current store is running the <tt style="font-weight: normal;"><?php echo $this->getCurrentThemePackage()->getPackageTheme() ?></tt> theme.  The DIY Mage generated CSS file will not be included on pages associated with this store.</span></li></ul></li></ul>
    <?php endif ?>
    
    <?php if (count($this->getChild()) > 0): ?>
        <?php echo $this->getChildHtml() ?>
    <?php else: ?>
        <p>You don't seem to have any controls loaded for still store.</p>
        <a href="<?php echo $this->getUrl('diy/design/rebuild', array('store_id' => $this->getStoreId())) ?>">Build/Rebuild Controls &rarr;</a>
    <?php endif ?>
</form>

<script type="text/javascript" charset="utf-8">
<!--
$j(function () {
    // Slider toggles
    $j(".subgroup:first div.content").slideToggle('slow');
    $j(".subgroup:first h3").toggleClass('open');


    // Update the font controls with the currently selected font
    var update_font_family = function (el) {
        $j(el).css('font-family', $j(el).val());
    }

    $j('.control.font select').each(function (i) {
        update_font_family($j(this));

        $j(this).change(function () {
            update_font_family($j(this));
        });
    });
})
-->
</script>
