<p class="diy control builder">
    <label>Builder</label>
    <span class="help">Complete control over the layout of your page.  Add static blocks, widgets and manually remove preinserted blocks.  How freakin' cool is that?</span>
    <span id="builder_canvas"></span>
</p>

<script type="text/javascript" charset="utf-8">
<!--
    var references = {
        "left": <?php echo $this->getLayoutReferenceJson('left') ?>,
        "right": <?php echo $this->getLayoutReferenceJson('right') ?>,
        "content": <?php echo $this->getLayoutReferenceJson('content') ?>
    };

    document.observe("dom:loaded", function () {
        updateLayoutBuilder();

        $('layout').observe('change', function (e) {
            updateLayoutBuilder();
        });
    });
    
    function updateLayoutBuilder() {
        var layout = $('layout').getValue();
        var configuration = [];
        
        if (layout.match(/2/) && layout.match(/left/)) {
            configuration.push(
                {
                    key: "left",
                    label: "Left Column"
                },
                {
                    key: "content",
                    label: "Main"
                }
            );
        } else if (layout.match(/2/) && layout.match(/right/)) {
                configuration.push(
                    {
                        key: "content",
                        label: "Main"
                    },
                    {
                        key: "right",
                        label: "Right Column"
                    }
                );
        } else if (layout.match(/3/)) {
            configuration.push(
                {
                    key: "left",
                    label: "Left Column"
                },
                {
                    key: "content",
                    label: "Main"
                },
                {
                    key: "right",
                    label: "Right Column"
                }
            );
        } else {
            configuration.push(
                {
                    key: "content",
                    label: "Main"
                }
            );
        }
        
        drawLayoutBuilder(configuration);
    }
    

    function drawLayoutBuilder(configuration) {
        var container = $('builder_canvas');
        var html = "";
        
        for ( var i = 0; i < configuration.length; i++ ) {
            var container_id = "<?php echo $this->getFieldId() ?>_" + i;
                    
            html += "<div class='container' id='" + container_id + "'>";
                html += "<b>" + configuration[i].label + "</b>";
                html += "<ul class='container_canvas' id='container_" + configuration[i].key + "'>";
                
                    for ( var j = 0; j < references[configuration[i].key].length; j++ ) {
                        html += drawLayoutBlock(references[configuration[i].key][j].name);
                    }
                
                html += "</ul>";
            html += "</div>";
            
            $j("#container_" + configuration[i].key).sortable();
        }
        
        container.update(html);
    }
    
    function drawLayoutBlock(name) {
        var html = "";
        
        html += "<li class='block'>";
            html += name;
        html += "</li>";
        
        return html;
    }
-->
</script>