<?php
/**
 * @see Meanbee_Diy_Block_Admin_Control_Unit_Abstract
 * @author Nicholas Jones
 */
?>
<p>
    <label for="<?php echo $this->getFieldName() ?>"><?php echo $this->getLabel() ?></label>
    <input type="text" name="<?php echo $this->getFieldName() ?>" id="<?php echo $this->getFieldId() ?>" value="<?php echo $this->getValue() ?>" /><?php echo $this->getUnit() ?><br />
    <i><?php echo $this->getHelpText() ?></i>
</p>