<!-- FOOTER --> 
<footer> 
    <?php echo $this->getChildHtml('footer.promo') ?>
    <section> 
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('diymage_footer_column_1')->toHtml(); ?>
    </section> 
    <section> 
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('diymage_footer_column_2')->toHtml(); ?>
    </section> 
    <section> 
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('diymage_footer_column_3')->toHtml(); ?>
    </section> 
    <section class="vcard"> 
        <h2>Stay Updated</h2> 
        <ul> 
            <li><a href="#" class="url facebook">Facebook</a></li> 
            <li><a href="#" class="url twitter">Twitter</a></li> 
            <li><a href="#" class="url youtube">Youtube</a></li> 
            <li><a href="#" class="url rss">RSS</a></li> 
        </ul> 
        <address> 
            <ul> 
                <li class="fn n">Company Name</li> 
                <li class="street-address">1 Address Road</li> 
                <li class="locality">City</li> 
                <li class="postal-code">PO5 7CO</li> 
                <li class="country-name">Country</li> 
                <li class="tel">01234 567890</li> 
            </ul> 
        </address> 
    </section> 
    <small><?php echo $this->getCopyright() ?></small>
</footer> 
<!-- END FOOTER -->