<!-- FOOTER --> 
<footer> 
    <!-- PROMO BAR --> 
    <section id="promo"> 
        <!-- PROMO TEXT --> 
        <div class="block block-promo-text"> 
            <div class="block-title"> 
                This is some promo text!12341
            </div> 
        </div> 
        <!-- END PROMO TEXT --> 
        <?php echo $this->getChildHtml("newsletter") ?>
    </section> 
    <!-- END PROMO BAR --> 
    <section> 
        <h2>Information</h2> 
        <ul class="links"> 
            <li><a href="#">About Us</a></li> 
            <li><a href="#">Contact Us</a></li> 
            <li><a href="#">Terms &amp; Conditions</a></li> 
            <li><a href="#">Shipping &amp; Returns</a></li> 
            <li><a href="#">Customer Services</a></li> 
            <li><a href="#">Stores and Locations</a></li> 
        </ul> 
    </section> 
    <section> 
        <h2>Popular Categories</h2> 
        <ul class="links"> 
            <li><a href="#">Category Two</a></li> 
            <li><a href="#">Catergory Type A</a></li> 
            <li><a href="#">Cat One</a></li> 
            <li><a href="#">Category Type D</a></li> 
        </ul> 
    </section> 
    <section> 
        <h2>Another List</h2> 
        <ul class="links"> 
            <li><a href="#">List item one</a></li> 
            <li><a href="#">List item two</a></li> 
            <li><a href="#">List item three</a></li> 
            <li><a href="#">List item four</a></li> 
            <li><a href="#">List item five</a></li> 
            <li><a href="#">List item six</a></li> 
        </ul> 
    </section> 
    <section class="vcard"> 
        <h2>Stay Updated</h2> 
        <ul> 
            <li><a href="#" class="url facebook">Facebook</a></li> 
            <li><a href="#" class="url twitter">Twitter</a></li> 
            <li><a href="#" class="url youtube">Youtube</a></li> 
            <li><a href="#" class="url rss">RSS</a></li> 
        </ul> 
        <address> 
            <ul> 
                <li class="fn n">Company Name</li> 
                <li class="street-address">1 Address Road</li> 
                <li class="locality">City</li> 
                <li class="postal-code">PO5 7CO</li> 
                <li class="country-name">Country</li> 
                <li class="tel">01234 567890</li> 
            </ul> 
        </address> 
    </section> 
    <small><?php echo $this->getCopyright() ?></small>
</footer> 
<!-- END FOOTER -->