<!-- FOOTER --> 
<footer> 
    <?php echo $this->getChildHtml('footer.promo') ?>
    <section> 
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('diymage_footer_column_1')->toHtml(); ?>
    </section> 
    <section> 
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('diymage_footer_column_2')->toHtml(); ?>
    </section> 
    <section> 
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('diymage_footer_column_3')->toHtml(); ?>
    </section> 
    <section class="vcard"> 
        <h2>Stay Updated</h2> 
        <ul> 
            <?php if ($facebook = Mage::getStoreConfig('diy/theme/facebook')): ?>
                <li><a href="http://www.facebook.com/<?php echo $this->escapeHtml($facebook) ?>" class="url facebook">Facebook</a></li>
            <?php endif ?>
            <?php if ($twitter = Mage::getStoreConfig('diy/theme/twitter')): ?>
                <li><a href="http://www.twitter.com/<?php echo $this->escapeHtml($twitter) ?>" class="url twitter">Twitter</a></li>
            <?php endif ?>
            <?php if ($youtube = Mage::getStoreConfig('diy/theme/youtube')): ?>
                <li><a href="http://www.youtube.com/<?php echo $this->escapeHtml($youtube) ?>" class="url youtube">Youtube</a></li>
            <?php endif ?>
            <?php if (Mage::getStoreConfig('rss/config/active')): ?>
                <li><a href="<?php echo $this->getUrl('rss') ?>" class="url rss">RSS</a></li> 
            <?php endif ?>
        </ul> 
        <address> 
            <ul> 
                <li class="fn n"><?php echo Mage::getStoreConfig('general/store_information/name') ?></li> 
                <?php $address = explode("\n", Mage::getStoreConfig('general/store_information/address')) ?>
                <?php foreach ($address as $line): ?>
                    <li class="adr"><?php echo $line ?></li>
                <?php endforeach ?>
                <li class="tel"><?php echo Mage::getStoreConfig('general/store_information/phone') ?></li> 
            </ul> 
        </address> 
    </section> 
    <small><?php echo $this->getCopyright() ?></small>
</footer> 
<!-- END FOOTER -->