<!-- SEARCH --> 
<form id="search-form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="GET"> 
    <label for="search"><?php echo $this->__('Search') ?></label> 
    <input type="search" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" id="search" placeholder="<?php echo $this->__('Search the store...') ?>" /> 
    <button value="Search" type="submit" class="button"><?php echo $this->__('Search') ?></button> 
</form> 
<!-- END SEARCH -->