<?php
/** @var $diy Meanbee_Diy_Helper_Theme */
$diy = Mage::helper('diy/theme');
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>"> 
<head> 
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass() ? ' class="'.$diy->expandBodyClass($this->getBodyClass()).'"' : '' ?>>
    <?php echo $this->getChildHtml('header') ?>
    <?php echo $this->getChildHtml('catalog.navigation') ?>
    <!-- LAYOUT (2 COLUMN RIGHT) -->
    <div class="main-container col2-right-layout">
        <?php echo $this->getChildHtml('global_messages') ?>
        <div class="main">
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            <div class="col-main">
                <?php echo $this->getChildHtml('content') ?>
            </div>
            <div class="col-right sidebar">
                <?php echo $this->getChildHtml('right') ?>
            </div>
        </div>
    </div>
    <!-- END LAYOUT (2 COLUMN RIGHT) -->
    <?php echo $this->getChildHtml('footer') ?>
</body>
</html>