<?php
/** @var $diy Meanbee_Diy_Helper_Theme */
$diy = Mage::helper('diy/theme');
?>
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="<?php echo $this->getLang() ?>"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie9 lt-ie8" lang="<?php echo $this->getLang() ?>"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie9" lang="<?php echo $this->getLang() ?>"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="" lang="<?php echo $this->getLang() ?>"> <!--<![endif]-->
<head> 
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass() ? ' class="'.$diy->expandBodyClass($this->getBodyClass()).'"' : '' ?>>
    <?php echo $this->getChildHtml('header') ?>
    <?php echo $this->getChildHtml('catalog.navigation') ?>
    <!-- LAYOUT (3 COLUMN) -->
    <div class="main-container col3-layout">
        <?php echo $this->getChildHtml('global_notices') ?>
        <div class="main">
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            <div class="col-left sidebar">
                <?php echo $this->getChildHtml('left') ?>
            </div>
            <div class="col-main">
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            </div>
            <div class="col-right sidebar">
                <?php echo $this->getChildHtml('right') ?>
            </div>
        </div>
    </div>
    <!-- END LAYOUT (3 COLUMN) -->
    <?php echo $this->getChildHtml('footer') ?>
</body>
</html>
