<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<!-- PRODUCT -->
<section class="hproduct hreview">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
    
        <div id="photos"> 
            <?php echo $this->getChildHtml('media') ?>
        </div> 
        <h1 class="product-name item"> 
            <strong class="fn" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></strong> 
        </h1> 
        <?php echo $this->getPriceHtml($_product) ?>
        
        <?php // Show review summary only if reviews are turned on in DIY Mage ?>
        <?php if (Mage::helper('diy')->getValue("catalog_product_view", "show_reviews") > 0): ?>
            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
        <?php endif;?>
        
        <div class="description quick"> 
            <?php echo $_product->getShortDescription() ?>
        </div> 
        <?php echo $this->getChildHtml('alert_urls') ?>
        
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
             <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
        <?php endif;?>
         
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>

        <?php echo $this->getChildHtml('product_type_data') ?>
        <?php echo $this->getTierPriceHtml() ?>
        <?php echo $this->getChildHtml('extrahint') ?>

        <?php if (!$this->hasOptions()):?>
            <div class="actions"> 
                <?php if($_product->isSaleable()): ?>
                    <?php echo $this->getChildHtml('addtocart') ?>
                <?php endif; ?>
                <?php echo $this->getChildHtml('addto') ?>
            </div>
            <?php echo $this->getChildHtml('extra_buttons') ?>
        <?php endif; ?>
    
        <?php echo $this->getChildHtml('social.links'); ?>
        
    </form>
    <script type="text/javascript">
     //<![CDATA[
         var productAddToCartForm = new VarienForm('product_addtocart_form');
         productAddToCartForm.submit = function(button, url) {
             if (this.validator.validate()) {
                 var form = this.form;
                 var oldUrl = form.action;

                 if (url) {
                    form.action = url;
                 }
                 var e = null;
                 try {
                     this.form.submit();
                 } catch (e) {
                 }
                 this.form.action = oldUrl;
                 if (e) {
                     throw e;
                 }

                 if (button && button != 'undefined') {
                     button.disabled = true;
                 }
             }
         }.bind(productAddToCartForm);

         productAddToCartForm.submitLight = function(button, url){
             if(this.validator) {
                 var nv = Validation.methods;
                 delete Validation.methods['required-entry'];
                 delete Validation.methods['validate-one-required'];
                 delete Validation.methods['validate-one-required-by-name'];
                 if (this.validator.validate()) {
                     if (url) {
                         this.form.action = url;
                     }
                     this.form.submit();
                 }
                 Object.extend(Validation.methods, nv);
             }
         }.bind(productAddToCartForm);
     //]]>
     </script>

    <?php // Additional Information ?>
    <?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php echo "box-{$alias}"?>">
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
    <?php endforeach;?>
    <?php echo $this->getChildHtml('product_additional_data') ?>
              
    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('product.tags') ?>
    
</section> 
<!-- END PRODUCT -->
