<?php $_productCollection=$this->getLoadedProductCollection() ?>
<!-- PRODUCTS LIST -->
<ul class="products-grid list-products">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="hproduct hreview<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>"> 
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName() ?>" class="product-image"> 
                <img class="photo" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200, 200); ?>" width="200" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
            </a> 
            <h2 class="product-name item"> 
                <a href="<?php echo $_product->getProductUrl() ?>" class="fn" title="<?php echo $_product->getName() ?>"><?php echo $_product->getName() ?></a> 
            </h2> 
            <?php if($_product->getRatingSummary()): ?>
            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            <?php endif; ?>
            <abbr class="rating stars-2-0" title="2 out of 5 stars"><span>2</span></abbr> 
            <a href="#" class="review-amount">8 Review(s)</a>                   
            <a href="#" class="link-review">Write a review</a> 
            <div class="description quick"> 
                <p><?php echo nl2br($_product->getShortDescription()) ?></p> 
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="link-more"><?php echo $this->__('Learn More') ?></a>
            </div> 
            <?php echo $this->getPriceHtml($_product, true) ?>
            <div class="actions"> 
                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></button> 
                 <ul class="add-to-links">
                     <?php if ($this->helper('wishlist')->isAllow()): ?>
                         <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li> 
                     <?php endif ?>
                     <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                         <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare')?></a></li>
                     <?php endif ?>
                </ul>
            </div> 
        </li>
    <?php endforeach ?>
</ul>
<!-- END PRODUCTS LIST -->
