<?php
/**
 * @see Mage_Catalog_Block_Product_View
 */

$_product = $this->getProduct();
$_tierPrices = $this->getTierPrices();
$_finalPriceInclTax = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice(), true);

$_weeeTaxAmount = Mage::helper('weee')->getAmountForDisplay($_product);
if (Mage::helper('weee')->typeOfDisplay($_product, array(1,2,4))) {
    $_weeeTaxAttributes = Mage::helper('weee')->getProductWeeeAttributesForDisplay($_product);
}

?>

<?php if (count($_tierPrices) > 0): ?>
    <?php if ($this->getInGrouped()): ?>
        <?php $_tierPrices = $this->getTierPrices($_product); ?>
    <?php endif; ?>
    <?php Mage::helper('weee')->processTierPrices($_product, $_tierPrices); ?>
    <!-- TIERED PRICING -->
    <aside class="tiered-pricing<?php echo ($this->getInGrouped() ? ' tiered-pricing-grouped' : ''); ?>"> 
        <ul> 
            <?php foreach ($_tierPrices as $_price): ?>
                <?php if ($this->helper('tax')->displayBothPrices()): ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_product, 0)): ?>
                        <li><?php echo $this->__('Buy %1$s for %2$s (%3$s incl. tax) each', $_price['price_qty'], $_price['formated_price_incl_weee_only'], $_price['formated_price_incl_weee']) ?>
                    <?php elseif(Mage::helper('weee')->typeOfDisplay($_product, 1)): ?>
                        <li><?php echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_weee_only']); ?>
                            <?php if ($_weeeTaxAttributes): ?>
                            (<small>
                            <?php echo $this->__('%1$s incl tax.', $_price['formated_price_incl_weee']); ?>
                            <?php $separator = ' + '; foreach ($_weeeTaxAttributes as $_attribute): ?>
                                <?php echo $separator; ?>
                                <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('core')->currency($_attribute->getAmount()); ?>
                            <?php endforeach; ?>
                            </small>)
                            <?php endif; ?>
                            <?php echo $this->__('each') ?>
                    <?php elseif(Mage::helper('weee')->typeOfDisplay($_product, 4)): ?>
                        <li><?php echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_weee_only']); ?>
                            <?php if ($_weeeTaxAttributes): ?>
                            (<small>
                            <?php echo $this->__('%1$s incl tax.', $_price['formated_price_incl_weee']); ?>
                            <?php $separator = ' + '; foreach ($_weeeTaxAttributes as $_attribute): ?>
                                <?php echo $separator; ?>
                                <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('core')->currency($_attribute->getAmount()+$_attribute->getTaxAmount()); ?>
                            <?php endforeach; ?>
                            </small>)
                            <?php endif; ?>
                            <?php echo $this->__('each') ?>
                    <?php elseif(Mage::helper('weee')->typeOfDisplay($_product, 2)): ?>
                        <li><?php echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price']); ?>
                            <?php if ($_weeeTaxAttributes): ?>
                            (<small>
                            <?php foreach ($_weeeTaxAttributes as $_attribute): ?>
                                <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('core')->currency($_attribute->getAmount()); ?>
                            <?php endforeach; ?>
                            <?php echo $this->__('Total incl. Tax: %1$s', $_price['formated_price_incl_weee']); ?>
                            </small>)
                            <?php endif; ?>
                            <?php echo $this->__('each') ?>
                    <?php else: ?>
                        <li><?php echo $this->__('Buy %1$s for %2$s (%3$s incl. tax) each', $_price['price_qty'], $_price['formated_price'], $_price['formated_price_incl_tax']) ?>
                    <?php endif; ?>
                <?php else: ?>
                    <?php if ($this->helper('tax')->displayPriceIncludingTax()): ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_product, 0)): ?>
                            <li><?php echo $this->__('Buy %1$s for %2$s each', $_price['price_qty'], $_price['formated_price_incl_weee']) ?>
                        <?php elseif(Mage::helper('weee')->typeOfDisplay($_product, 1)): ?>
                            <li><?php echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_weee']); ?>
                                <?php if ($_weeeTaxAttributes): ?>
                                (</small>
                                <?php $separator = ''; foreach ($_weeeTaxAttributes as $_attribute): ?>
                                    <?php echo $separator; ?>
                                    <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('core')->currency($_attribute->getAmount()); ?>
                                <?php $separator = ' + '; endforeach; ?>
                                <small>)
                                <?php endif; ?>
                                <?php echo $this->__('each') ?>
                        <?php elseif(Mage::helper('weee')->typeOfDisplay($_product, 4)): ?>
                            <li><?php echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_weee']); ?>
                                <?php if ($_weeeTaxAttributes): ?>
                                (</small>
                                <?php $separator = ''; foreach ($_weeeTaxAttributes as $_attribute): ?>
                                    <?php echo $separator; ?>
                                    <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('core')->currency($_attribute->getAmount()+$_attribute->getTaxAmount()); ?>
                                <?php $separator = ' + '; endforeach; ?>
                                <small>)
                                <?php endif; ?>
                                <?php echo $this->__('each') ?>
                        <?php elseif(Mage::helper('weee')->typeOfDisplay($_product, 2)): ?>
                            <li><?php echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_tax']); ?>
                                <?php if ($_weeeTaxAttributes): ?>
                                (<small>
                                <?php foreach ($_weeeTaxAttributes as $_attribute): ?>
                                    <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('core')->currency($_attribute->getAmount()); ?>
                                <?php endforeach; ?>
                                <?php echo $this->__('Total incl. Tax: %1$s', $_price['formated_price_incl_weee']); ?>
                                </small>)
                                <?php endif; ?>
                                <?php echo $this->__('each') ?>
                        <?php else: ?>
                            <li><?php echo $this->__('Buy %1$s for %2$s each', $_price['price_qty'], $_price['formated_price_incl_tax']) ?>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_product, 0)): ?>
                            <li><?php echo $this->__('Buy %1$s for %2$s each', $_price['price_qty'], $_price['formated_price_incl_weee_only']) ?>
                        <?php elseif(Mage::helper('weee')->typeOfDisplay($_product, 1)): ?>
                            <li><?php echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_weee_only']); ?>
                                <?php if ($_weeeTaxAttributes): ?>
                                (<small>
                                <?php $separator = ''; foreach ($_weeeTaxAttributes as $_attribute): ?>
                                    <?php echo $separator; ?>
                                    <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('core')->currency($_attribute->getAmount()); ?>
                                <?php $separator = ' + '; endforeach; ?>
                                </small>)
                                <?php endif; ?>
                                <?php echo $this->__('each') ?>
                        <?php elseif(Mage::helper('weee')->typeOfDisplay($_product, 4)): ?>
                            <li><?php echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price_incl_weee_only']); ?>
                                <?php if ($_weeeTaxAttributes): ?>
                                (<small>
                                <?php $separator = ''; foreach ($_weeeTaxAttributes as $_attribute): ?>
                                    <?php echo $separator; ?>
                                    <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('core')->currency($_attribute->getAmount()+$_attribute->getTaxAmount()); ?>
                                <?php $separator = ' + '; endforeach; ?>
                                </small>)
                                <?php endif; ?>
                                <?php echo $this->__('each') ?>
                        <?php elseif(Mage::helper('weee')->typeOfDisplay($_product, 2)): ?>
                            <li><?php echo $this->__('Buy %1$s for %2$s', $_price['price_qty'], $_price['formated_price']); ?>
                                <?php if ($_weeeTaxAttributes): ?>
                                (<small>
                                <?php foreach ($_weeeTaxAttributes as $_attribute): ?>
                                    <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('core')->currency($_attribute->getAmount()); ?>
                                <?php endforeach; ?>
                                <?php echo $this->__('Total incl. Tax: %1$s', $_price['formated_price_incl_weee_only']); ?>
                                </small>)
                                <?php endif; ?>
                                <?php echo $this->__('each') ?>
                        <?php else: ?>
                            <li><?php echo $this->__('Buy %1$s for %2$s each', $_price['price_qty'], $_price['formated_price']) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if (!$this->getInGrouped()): ?>
                    <?php if(($_product->getPrice() == $_product->getFinalPrice() && $_product->getPrice() > $_price['price'])
                    || ($_product->getPrice() != $_product->getFinalPrice() &&  $_product->getFinalPrice() > $_price['price'])): ?>
                        <?php echo $this->__('and') ?>&nbsp;<strong class="benefit"><?php echo $this->__('save')?>&nbsp;<?php echo $_price['savePercent']?>%
                    <?php endif ?></strong>
                <?php endif; ?>
                </li>
            <?php endforeach ?>
        </ul> 
    </aside> 
    <!-- END TIERED PRICING -->
<?php endif ?>