<?php
/**
 * @TODO: Use a checkbox instead of a dropdown..
 *
 * @see Meanbee_Diy_Block_Admin_Control_Boolean
 */
?>
<p class="diy control boolean">
    <select name="<?php echo $this->getFieldName() ?>" data-default="<?php echo $this->getDefaultValue() ?>" id="<?php echo $this->getFieldId() ?>">
        <option value="1"<?php if ($this->getValue() == "1"):?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
        <option value="0"<?php if ($this->getValue() == "0"):?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
    </select>
    <label for="<?php echo $this->getFieldName() ?>"><?php echo $this->getLabel() ?></label>
</p>