<?php
/**
 * @see Meanbee_Diy_Block_Admin_Control_Dropdown
 * @author Nicholas Jones
 */
?>
<div class="diy control dropdown">
    <div class="input">
        <select name="<?php echo $this->getFieldName() ?>" data-default="<?php echo $this->getDefaultValue() ?>" id="<?php echo $this->getFieldId() ?>">
            <?php foreach ($this->getOptions() as $key => $value): ?>
                <option value="<?php echo $key ?>"<?php if ($this->getValue() == $key):?> selected="selected"<?php endif ?>><?php echo $value ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <label for="<?php echo $this->getFieldName() ?>"><?php echo $this->getLabel() ?></label>
</div>