<?php
/**
 * @see Meanbee_Diy_Block_Admin_Control_Dropdown
 * @author Nicholas Jones
 */
?>
<p class="diy control dropdown">
    <label for="<?php echo $this->getFieldName() ?>"><?php echo $this->getLabel() ?></label>
    <select name="<?php echo $this->getFieldName() ?>" data-default="<?php echo $this->getDefaultValue() ?>" id="<?php echo $this->getFieldId() ?>">
        <?php foreach ($this->getOptions() as $key => $value): ?>
            <option value="<?php echo $key ?>"<?php if ($this->getValue() == $key):?> selected="selected"<?php endif ?>><?php echo $value ?></option>
        <?php endforeach ?>
    </select>
</p>