<?php
// {{license}}
?>
<?php
/**
 * @see Meanbee_Diy_Block_Admin_Control_Font
 * @author Nicholas Jones
 */
?>
<div class="diy control dropdown font">
    <div class="input">
        <select name="<?php echo $this->getFieldName() ?>" id="<?php echo $this->getFieldId() ?>">
            <?php foreach ($this->getOptions() as $key => $value): ?>
                <option value="<?php echo $value ?>"<?php if ($this->getValue() == $value):?> selected="selected"<?php endif ?>><?php echo $value ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <label for="<?php echo $this->getFieldName() ?>"><?php echo $this->getLabel() ?></label>
</div>
