<?php
/**
 * @see Meanbee_Diy_Block_Admin_Control_Unit_Abstract
 * @author Nicholas Jones
 */
?>
<div class="diy control unit">
    <div class="input">
        <input type="text" data-default="<?php echo $this->getDefaultValue() ?>" name="<?php echo $this->getFieldName() ?>" id="<?php echo $this->getFieldId() ?>" value="<?php echo $this->getValue() ?>" /><span class="unit"><?php echo $this->getUnit() ?></span>
    </div>
    <label for="<?php echo $this->getFieldName() ?>"><?php echo $this->getLabel() ?></label>
</div>
