<h1><?php echo $this->__('Login or Create An Account') ?></h1>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="col2-set"> 
    <div class="col-1"> 
        <h2><?php echo $this->__('New Customers') ?></h2> 
        <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p> 
        <div class="buttons-set"> 
            <button type="button" class="button" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';"><?php echo $this->__('Create an Account') ?></button> 
        </div> 
    </div> 
    <div class="col-2"> 
        <h2><?php echo $this->__('Registered Customers') ?></h2> 
        <form id="login-form" action="<?php echo $this->getPostActionUrl() ?>" method="post"> 
            <fieldset> 
                <h3><?php echo $this->__('If you have an account with us, please log in.') ?></h3> 
                <ul> 
                    <li> 
                        <label for="login-email" class="required"><em class="required">*</em><?php echo $this->__('Email Address') ?></label> 
                        <input type="email" class="text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" /> 
                    </li> 
                    <li> 
                        <label for="login-password" class="required"><em class="required">*</em><?php echo $this->__('Password') ?></label> 
                        <input type="password" class="text required-entry" id="login-password" name="login[password]" /> 
                    </li> 
                </ul> 
            </fieldset> 
            <div class="buttons-set"> 
                <p class="required"><?php echo $this->__('* Required Fields') ?></p> 
                <a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Forgot your password?') ?></a> 
                <button type="submit" title="<?php echo $this->__('Login') ?>" class="button"><?php echo $this->__('Login') ?></button> 
            </div> 
        </form> 
    </div> 
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('login-form', true);
//]]>
</script>