<!-- <div id="diymage_hint_viewer">
    HINT VIEWER.
</div> -->


<style type="text/css" media="screen">
<!--
#diymage_hint_viewer {
    position: fixed;
    right: 0;
    top: 0;
    bottom: 0;
    
    width: 325px;
    
    color: white;
    background: #333;
    opacity: 0.95;
}

/** Actual Hints **/

/*.diy-hint {
    outline: red dotted 1px;
    position: relative;
    cursor: pointer;
    font-size: 11px;
    min-height: 10px;
}

.diy-hint:after {
    content: ".";
    display: block;
    height: 0;
    clear: both;
    visibility: hidden;
}

.diy-hint .inner {
    display: none;
    text-align: left;
}

.diy-hint:hover > .inner {
    display: block;
    position: absolute;
    top: 0; left: 0;
    background-color: red;
    color: white;
    height: 36px;
    width: 100%;
    padding: 3px;
    z-index: 9000;
}

.diy-hint:hover > .inner {
    width: auto;
}

.diy-hint:hover > .shade {
    position: absolute;
    top: 0; left: 0; bottom: 0; right: 0;
    background: red;
    opacity: 0.15;
}*/
-->
</style>

<script type="text/javascript" charset="utf-8">
jQuery('diy-hint').each(function () {
    
});
</script>