<!DOCTYPE html> 
<html lang="<?php echo $this->getLang() ?>"> 
<head> 
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass() ? ' class="'.$this->getBodyClass().'"' : '' ?>>
    <?php echo $this->getChildHtml('header') ?>
    <?php echo $this->getChildHtml('catalog.navigation') ?>
    <!-- LAYOUT (1 COLUMN) -->
    <div class="main-container col1-layout">
        <?php echo $this->getChildHtml('global_messages') ?>
        <div class="main">
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            <div class="col-main">
                <?php echo $this->getChildHtml('content') ?>
            </div>
        </div>
    </div>
    <!-- END LAYOUT (1 COLUMN) -->
    <?php echo $this->getChildHtml('footer') ?>
</body>
</html>