<?php
function renderCategoryChildren($category, $block) {
    ?>
    <li>
        <a href="<?php echo $block->getCategoryUrl($category) ?>"><?php echo $category->getName() ?></a>
        <?php if ($category->getChildren()->count() > 0): ?>
            <ul>
            <?php foreach ($category->getChildren() as $child): ?>
                <?php renderCategoryChildren($child, $block) ?>
            <?php endforeach ?>
            </ul>
        <?php endif ?>
    </li>
    <?php
}
?>
<!-- SHOP NAVIGATION --> 
<nav> 
    <ul>
        <?php foreach ($this->getStoreCategories() as $child): ?>
            <?php if ($child->getIsActive()): ?>
                <?php renderCategoryChildren($child, $this) ?>
            <?php endif ?>
        <?php endforeach ?>
    </ul> 
</nav> 
<!-- END SHOP NAVIGATION -->