<?php
function renderCategoryChildren($category, $block, $top = false) {
    ?>
    <li<?php if($block->isCategoryActive($category)) { echo ' class="active"'; } ?>>
        <a href="<?php echo $block->getCategoryUrl($category) ?>"<?php if ($top) { echo ' class="level-top"'; } ?>><?php echo $category->getName() ?></a>
        <?php if ($category->getChildren()->count() > 0): ?>
            <ul>
            <?php foreach ($category->getChildren() as $child): ?>
                <?php renderCategoryChildren($child, $block) ?>
            <?php endforeach ?>
            </ul>
        <?php endif ?>
    </li>
    <?php
}
?>
<!-- SHOP NAVIGATION --> 
<nav> 
    <ul>
        <?php foreach ($this->getStoreCategories() as $child): ?>
            <?php if ($child->getIsActive()): ?>
                <?php renderCategoryChildren($child, $this, true) ?>
            <?php endif ?>
        <?php endforeach ?>
    </ul> 
</nav> 
<!-- END SHOP NAVIGATION -->