<?php
// {{license}}
?>
<?php
    // Put this in a variable to make typing quicker.
    $d = Mage::helper('diy');
?>
body {
    <?php echo $this->getStyleLine('global', 'font_size', 'font-size', '%spx') ?>
    <?php echo $this->getStyleLine('global', 'font_colour', 'color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'body_background_image', 'background-image', 'url("images/diy/%s")') ?>
    <?php echo $this->getStyleLine('global', 'body_background_position', 'background-position', '%s') ?>
    <?php echo $this->getStyleLine('global', 'body_background_repeat', 'background-repeat', '%s') ?>
    <?php echo $this->getStyleLine('global', 'body_background_colour', 'background-color', '#%s') ?>
}

a {
    <?php echo $this->getStyleLine('global', 'link_colour', 'color', '#%s') ?>
}

a:hover {
    <?php echo $this->getStyleLine('global', 'link_hover_colour', 'color', '#%s') ?>
}

input, select, textarea {
    <?php echo $this->getStyleLine('global', 'input_colour', 'color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'input_font_family', 'font-family') ?>
    <?php echo $this->getStyleLine('global', 'input_font_size', 'font-size', '%spx') ?>
}

button { 
    <?php echo $this->getStyleLine('global', 'button_colour', 'color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'input_font_family', 'font-family') ?>
    <?php echo $this->getStyleLine('global', 'input_font_size', 'font-size', '%spx') ?>
}

input.input-text, select, textarea {
    <?php echo $this->getStyleLine('global', 'input_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'button_colour', 'border-color', '#%s') ?>
}

input.input-text, textarea {
    <?php echo $this->getStyleLine('global', 'input_text_padding', 'padding', '%spx') ?>
}

.header, header {
    <?php echo $this->getStyleLine('global', 'header_background_image', 'background-image', 'url("images/diy/%s")') ?>
    <?php echo $this->getStyleLine('global', 'header_background_position', 'background-position', '%s') ?>
    <?php echo $this->getStyleLine('global', 'header_background_repeat', 'background-repeat', '%s') ?>
    <?php echo $this->getStyleLine('global', 'header_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'header_font_size', 'font-size', '%spx') ?>
    <?php echo $this->getStyleLine('global', 'header_text_colour', 'color', '#%s') ?>
}

.header .links a, header ul.site-navigation a {
    <?php echo $this->getStyleLine('global', 'header_link_colour', 'color', '#%s') ?>    
}

.header .links a:hover, header ul.site-navigation a:hover {
    <?php echo $this->getStyleLine('global', 'header_link_hover_colour', 'color', '#%s') ?>
}

#nav {
    <?php echo $this->getStyleLine('global', 'nav_bar_background', 'background-color', '#%s') ?>
}

#nav li {
    <?php echo $this->getStyleLine('global', 'nav_item_background', 'background-color', '#%s') ?>
}

#nav li a {
    <?php echo $this->getStyleLine('global', 'nav_item_link_colour', 'color', '#%s') ?>
}

#nav li.active a {
    <?php echo $this->getStyleLine('global', 'nav_item_active_link_colour', 'color', '#%s') ?>
}

#nav li a:hover {
    <?php echo $this->getStyleLine('global', 'nav_item_link_hover_colour', 'color', '#%s') ?>
}

#nav ul li a {
    <?php echo $this->getStyleLine('global', 'nav_sub_item_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'nav_sub_item_link_colour', 'color', '#%s') ?>
}

#nav ul li a:hover {
    <?php echo $this->getStyleLine('global', 'nav_sub_item_background_hover_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'nav_sub_item_link_hover_colour', 'color', '#%s') ?>
}

#nav ul, #nav div {
    <?php if ($d->getValue("global", "nav_sub_list_border" ) != 1): ?>
        border: none;
    <?php endif; ?>
    <?php echo $this->getStyleLine('global', 'nav_sub_list_border_colour', 'border-color', '#%s') ?>
}

.breadcrumbs {
    <?php echo $this->getStyleLine('global', 'breadcrumb_text_colour', 'color', '#%s') ?>
}

.breadcrumbs a {
    <?php echo $this->getStyleLine('global', 'breadcrumb_link_colour', 'color', '#%s') ?>
}

.breadcrumbs a:hover {
    <?php echo $this->getStyleLine('global', 'breadcrumb_link_hover_colour', 'color', '#%s') ?>
}

.breadcrumbs span {
    <?php echo $this->getStyleLine('global', 'breadcrumb_divider_colour', 'color', '#%s') ?>
}

.footer {
    <?php echo $this->getStyleLine('global', 'footer_text_colour', 'color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'footer_font_size', 'font-size', '%spx') ?>
}

.footer a {
    <?php echo $this->getStyleLine('global', 'footer_link_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'footer_link_colour', 'color', '#%s') ?>
}

.footer a:hover {
    <?php echo $this->getStyleLine('global', 'footer_link_hover_colour', 'color', '#%s') ?>
}

.footer li {
<?php if ($d->getValue("global", "footer_list_display") == 1): ?>
    display: inline;
<?php else: ?>
    display: block;
<?php endif; ?>
}

<?php if ($d->getValue("catalog_category_view", "pager_border") != 1): ?>
    .pager, .sorter {
        border: none;
    }
<?php endif ?>

.pager, .sorter {
    <?php echo $this->getStyleLine('catalog_category_view', 'pager_background', 'background-color', '#%s') ?>
}