<?php
// {{license}}
?>
<?php
    // Put this in a variable to make typing quicker.
    $d = Mage::helper('diy');
?>
body {
    <?php echo $this->getStyleLine('global', 'font_size', 'font-size', '%spx') ?>
    <?php echo $this->getStyleLine('global', 'font_colour', 'color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'body_background_image', 'background-image', 'url("images/diy/%s")') ?>
    <?php echo $this->getStyleLine('global', 'body_background_position', 'background-position', '%s') ?>
    <?php echo $this->getStyleLine('global', 'body_background_repeat', 'background-repeat', '%s') ?>
    <?php echo $this->getStyleLine('global', 'body_background_colour', 'background-color', '#%s') ?>
}

a {
    <?php echo $this->getStyleLine('global', 'link_colour', 'color', '#%s') ?>
}

a:hover {
    <?php echo $this->getStyleLine('global', 'link_hover_colour', 'color', '#%s') ?>
}

input, select, textarea {
    <?php echo $this->getStyleLine('global', 'input_colour', 'color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'input_font_family', 'font-family') ?>
    <?php echo $this->getStyleLine('global', 'input_font_size', 'font-size', '%spx') ?>
}

a.button,
input.button,
button {
    <?php echo $this->getStyleLine('global', 'button_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'button_colour', 'color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'input_font_size', 'font-size', '%spx') ?>
}

a.cart,
input.cart,
button.cart,
div.sidebar div.block button.cart {
    <?php echo $this->getStyleLine('global', 'button_cart_colour', 'color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'button_cart_background_colour', 'background-color', '#%s') ?>
}

a.simple-button,
input.simple-button,
button.simple-button {
    <?php echo $this->getStyleLine('global', 'button_aside_colour', 'color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'button_aside_background_colour', 'background-color', '#%s') ?>
}

input.input-text, select, textarea {
    <?php echo $this->getStyleLine('global', 'input_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'input_border_colour', 'border-color', '#%s') ?>
}

input.input-text, textarea {
    <?php echo $this->getStyleLine('global', 'input_text_padding', 'padding', '%spx') ?>
}

.header, header {
    <?php echo $this->getStyleLine('global', 'header_background_image', 'background-image', 'url("images/diy/%s")') ?>
    <?php echo $this->getStyleLine('global', 'header_background_position', 'background-position', '%s') ?>
    <?php echo $this->getStyleLine('global', 'header_background_repeat', 'background-repeat', '%s') ?>
    <?php echo $this->getStyleLine('global', 'header_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'header_font_size', 'font-size', '%spx') ?>
    <?php echo $this->getStyleLine('global', 'header_text_colour', 'color', '#%s') ?>
}

.header .links a, header ul.site-navigation a {
    <?php echo $this->getStyleLine('global', 'header_link_colour', 'color', '#%s') ?>    
}

.header .links a:hover, header ul.site-navigation a:hover {
    <?php echo $this->getStyleLine('global', 'header_link_hover_colour', 'color', '#%s') ?>
}

input[type="search"], input.search, input#search {
    <?php echo $this->getStyleLine('global', 'header_search_border_colour', 'border-color', '#%s') ?>
}

header section.cart {
    <?php echo $this->getStyleLine('global', 'header_cart_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'header_cart_border_colour', 'border-color', '#%s') ?>
}

nav,
#nav {
    <?php echo $this->getStyleLine('global', 'nav_bar_background', 'background-color', '#%s') ?>
}

nav ul li,
#nav li {
    <?php echo $this->getStyleLine('global', 'nav_item_background', 'background-color', '#%s') ?>
}

nav ul li a,
#nav li a {
    <?php echo $this->getStyleLine('global', 'nav_item_link_colour', 'color', '#%s') ?>
}

nav ul li:hover > a,
#nav li:hover > a {
    <?php echo $this->getStyleLine('global', 'nav_item_background_hover_colour', 'background-color', '#%s') ?>
}

nav ul li.active > a,
#nav li.active > a {
    <?php echo $this->getStyleLine('global', 'nav_item_active_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'nav_item_active_link_colour', 'color', '#%s') ?>
}

nav ul li a:hover,
#nav li a:hover {
    <?php echo $this->getStyleLine('global', 'nav_item_link_hover_colour', 'color', '#%s') ?>
}

nav ul li.active a:hover,
#nav li.active a:hover {
    <?php echo $this->getStyleLine('global', 'nav_item_active_link_hover_colour', 'color', '#%s') ?>
}

nav ul ul li a,
#nav ul li a {
    <?php echo $this->getStyleLine('global', 'nav_sub_item_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'nav_sub_item_link_colour', 'color', '#%s') ?>
}

nav ul ul li a:hover,
#nav ul li a:hover {
    <?php echo $this->getStyleLine('global', 'nav_sub_item_background_hover_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'nav_sub_item_link_hover_colour', 'color', '#%s') ?>
}

.breadcrumbs {
    <?php echo $this->getStyleLine('global', 'breadcrumb_text_colour', 'color', '#%s') ?>
}

.breadcrumbs a {
    <?php echo $this->getStyleLine('global', 'breadcrumb_link_colour', 'color', '#%s') ?>
}

.breadcrumbs a:hover, .breadcrumbs a:active {
    <?php echo $this->getStyleLine('global', 'breadcrumb_link_hover_colour', 'color', '#%s') ?>
}

.breadcrumbs span {
    <?php echo $this->getStyleLine('global', 'breadcrumb_divider_colour', 'color', '#%s') ?>
}

div.sidebar div.block {
<?php if ($d->getValue("global", "sidebar_block_rounded") == 0): ?>
    border-radius: 0;
    -moz-border-radius: 0;
<?php endif; ?>
<?php if ($d->getValue("global", "sidebar_block_text_shadow") == 0): ?>
    text-shadow: none;
<?php endif; ?>
    <?php echo $this->getStyleLine('global', 'sidebar_block_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'sidebar_block_border_colour', 'border-color', '#%s') ?>
}

div.sidebar div.block div.block-title {
    <?php echo $this->getStyleLine('global', 'sidebar_block_heading_separator_colour', 'border-color', '#%s') ?>
}

div.sidebar div.block div.block-title h2,
div.sidebar div.block div.block-title strong span {
    <?php echo $this->getStyleLine('global', 'sidebar_block_heading_colour', 'color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'sidebar_block_heading_size', 'font-size', '%spx') ?>
}

div.block-layered-nav dl#narrow-by-list dt,
div.block-cart div.summary h3, 
div.block-cart p.block-subtitle,
div.block-compare ol li, 
div.block-compare div.actions, 
div.block-cart ol li, 
div.block-cart div.actions, 
div.block-wishlist ol li, 
div.block-wishlist div.actions,
div.block-layered-nav p.block-subtitle,
div.block-viewed ol li {
    <?php echo $this->getStyleLine('global', 'sidebar_block_divider_colour', 'border-color', '#%s') ?>
}

div.sidebar div.block button,
div.sidebar div.block button span {
    <?php echo $this->getStyleLine('global', 'sidebar_button_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'sidebar_button_colour', 'color', '#%s') ?>
}

div.sidebar a {
    <?php echo $this->getStyleLine('global', 'sidebar_link_colour', 'color', '#%s') ?>
}

div.sidebar a:hover, div.sidebar a:active {
    <?php echo $this->getStyleLine('global', 'sidebar_link_hover_colour', 'color', '#%s') ?>
}

.footer, footer {
    <?php echo $this->getStyleLine('global', 'footer_background_image', 'background-image', 'url("images/diy/%s")') ?>
    <?php echo $this->getStyleLine('global', 'footer_background_position', 'background-position', '%s') ?>
    <?php echo $this->getStyleLine('global', 'footer_background_repeat', 'background-repeat', '%s') ?>
    <?php echo $this->getStyleLine('global', 'footer_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'footer_text_colour', 'color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'footer_font_size', 'font-size', '%spx') ?>
}

footer section#promo {
    <?php echo $this->getStyleLine('global', 'footer_promo_background_colour', 'background-color', '#%s') ?>
    <?php echo $this->getStyleLine('global', 'footer_promo_colour', 'color', '#%s') ?>
}

.footer a, footer a {
    <?php echo $this->getStyleLine('global', 'footer_link_colour', 'color', '#%s') ?>
}

.footer a:hover, footer a:hover {
    <?php echo $this->getStyleLine('global', 'footer_link_hover_colour', 'color', '#%s') ?>
}

.footer li, footer li {
<?php if ($d->getValue("global", "footer_list_display") == 1): ?>
    display: inline;
<?php else: ?>
    display: block;
<?php endif; ?>
}

footer small {
    <?php echo $this->getStyleLine('global', 'footer_copyright_colour', 'color', '#%s') ?>
    <?php if (!$d->getValue('global', 'show_footer_copyright_border')):?>
    border: 0;
    <?php else: ?>
    <?php echo $this->getStyleLine('global', 'footer_copyright_border_colour', 'border-color', '#%s') ?>
    <?php endif; ?>
}

<?php if ($d->getValue("catalog_category_view", "pager_border") != 1): ?>
    .pager, .sorter {
        border: none;
    }
<?php endif ?>

.pager, .sorter {
    <?php echo $this->getStyleLine('catalog_category_view', 'pager_background', 'background-color', '#%s') ?>
}