<!-- MINICART -->
<section class="cart">
    <?php if ($this->getSummaryCount() > 0): ?>
        <h2><a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Your Cart:') ?></a></h2>
    <?php else: ?>
        <h2><?php echo $this->__('Your Cart:') ?></h2>
    <?php endif; ?>
    <p>
        <?php if ($this->getSummaryCount() > 0): ?>
            <a href="<?php echo $this->getUrl('checkout/cart') ?>">
            <?php printf("%d item%s", $this->getSummaryCount(), ($this->getSummaryCount() > 1) ? "s" : "")?>
            <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
            (<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?>)
            <?php else: ?>
            (<?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>)
            <?php endif; ?>
            </a>
        <?php else: ?>
            <i><?php echo $this->__('Your cart is empty') ?></i>
        <?php endif ?>
    </p>
    <button type="button" onclick="setLocation('<?php echo $this->getUrl('checkout/onepage') ?>')" class="button cart"><?php echo $this->__('Checkout Now') ?></button>
</section>
<!-- END MINICART -->