<!-- MINICART -->
<section class="cart"> 
    <h2><?php echo $this->__('Your Cart:') ?></h2> 
    <p>
        <?php if ($this->getSummaryCount() > 0): ?>
            <?php printf("%d item%s", $this->getSummaryCount(), ($this->getSummaryCount() > 1) ? "s" : "")?>
            <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
            (<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?>)
            <?php else: ?>
            (<?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>)
            <?php endif; ?>
        <?php else: ?>
            <i><?php echo $this->__('Your cart is empty') ?></i>
        <?php endif ?>
    </p>
    <button type="button" class="button cart"><?php echo $this->__('Checkout Now') ?></button>
</section>
<!-- END MINICART -->