<?php $_shippingRateGroups = $this->getEstimateRates() ?>
<aside class="shipping">
    <h2><?php echo $this->__('Estimate Shipping and Tax') ?></h2>
    <form action="<?php echo $this->getUrl('checkout/cart/estimatePost') ?>" method="post" id="shipping-form"<?php echo ($_shippingRateGroups) ? ' style="display: none"' : '' ?>>
        <p><?php echo $this->__('Enter your destination to get a shipping estimate.') ?></p>
        <ul>
            <!-- COUNTRY START -->
            <li>
                <label for="country_id" class="required"><em class="required">*</em> <?php echo $this->__('Country') ?></label>
                <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId()) ?>
            </li>
            <!-- COUNTRY END -->
            <!-- PROVINCE START -->
            <?php $provinceRequired = $this->isStateProvinceRequired() ?>
            <li>
                <label for="region_id"<?php echo ($provinceRequired) ? ' class="required"' : '' ?>>
                    <?php echo ($provinceRequired) ? '<em class="required">*</em> ' : '' ?><?php echo $this->__('State/Province') ?>
                </label>
                <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>"<?php ($provinceRequired) ? ' class="validate-select"' : '' ?>>
                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>
               <input class="text" type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getEstimateRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" style="display:none;" />
               <script type="text/javascript">
               //<![CDATA[
                   $('region_id').setAttribute('defaultValue',  "<?php echo $this->getEstimateRegionId() ?>");
               //]]>
               </script>
            </li>
            <!-- PROVINCE END -->
            <?php if($this->getCityActive()): ?>
                <!-- CITY START -->
                <?php $cityRequired = $this->isCityRequired() ?>
                <li>
                    <label for="city"<?php echo ($cityRequired) ? ' class="required"' : '' ?>>
                        <?php echo ($cityRequired) ? '<em class="required">*</em> ' : '' ?><?php echo $this->__('City') ?>
                    </label>
                    <input class="text<?php echo ($cityRequired) ? ' required-entry' : ''?>" id="city" type="text" name="estimate_city" value="<?php echo $this->htmlEscape($this->getEstimateCity()) ?>" />
                </li>
                <!-- CITY END -->
            <?php endif; ?>
            <!-- POSTCODE START -->
            <?php $postcodeRequired = $this->isZipCodeRequired() ?>
            <li>
                <label for="postcode"<?php echo ($postcodeRequired) ? ' class="required"' : '' ?>>
                    <?php echo $this->__('Zip/Postal Code') ?>
                </label>
                <?php echo ($postcodeRequired) ? '<em class="required">*</em> ' : '' ?><input class="text validate-postcode<?php echo ($postcodeRequired) ? 'required' : '' ?>" type="text" id="postcode" name="estimate_postcode" value="<?php echo $this->htmlEscape($this->getEstimatePostcode()) ?>" />
            </li>
            <!-- POSTCODE END -->
        </ul>
        <button type="button" title="<?php echo $this->__('Get a Quote') ?>" onclick="coShippingMethodForm.submit()" class="button">Get a Quote</button>
    </form>

    <?php if (($_shippingRateGroups = $this->getEstimateRates())): ?>
        <form id="co-shipping-method-form" action="<?php echo $this->getUrl('checkout/cart/estimateUpdatePost') ?>">
            <dl class="sp-methods">
                <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                    <dt><?php echo $this->getCarrierName($code) ?></dt>
                    <dd>
                        <ul>
                        <?php foreach ($_rates as $_rate): ?>
                            <li<?php if ($_rate->getErrorMessage()) echo ' class="error-msg"';?>>
                               <?php if ($_rate->getErrorMessage()): ?>
                                    <?php echo $_rate->getErrorMessage() ?>
                               <?php else: ?>
                                    <input name="estimate_method" type="radio" value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio" />
                                    <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $_rate->getMethodTitle() ?>
                                    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                    <?php echo $_excl; ?>
                                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                    <?php endif; ?>
                                    </label>
                               <?php endif ?>
                            </li>
                        <?php endforeach; ?>
                        </ul>
                    </dd>
                <?php endforeach; ?>
            </dl>
            <button type="submit" title="<?php echo $this->__('Update Total') ?>" class="button" name="do" value="<?php echo $this->__('Update Total') ?>">
                <?php echo $this->__('Update Total') ?>
            </button>
            <a href="<?php echo $this->getUrl("*/*") ?>" onclick="$('co-shipping-method-form').hide(); $('shipping-form').show(); return false;"><?php echo $this->__('Try another address') ?></a>
        </form>
     <?php endif; ?>

    <script type="text/javascript">
    //<![CDATA[
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
    //]]>
    </script>
    <script type="text/javascript">
    //<![CDATA[
        var coShippingMethodForm = new VarienForm('shipping-form');
        var countriesWithOptionalZip = <?php echo $this->helper('directory')->getCountriesWithOptionalZip(true) ?>;

        coShippingMethodForm.submit = function () {
            var country = $F('country');
            var optionalZip = false;

            for (i=0; i < countriesWithOptionalZip.length; i++) {
                if (countriesWithOptionalZip[i] == country) {
                    optionalZip = true;
                }
            }
            if (optionalZip) {
                $('postcode').removeClassName('required-entry');
            }
            else {
                $('postcode').addClassName('required-entry');
            }
            return VarienForm.prototype.submit.bind(coShippingMethodForm)();
        }
    //]]>
    </script>
</aside>