<?php
class Meanbee_Diy_Model_Stylesheet {
    public function publish() {
        $block = Mage::getBlockSingleton('diy/stylesheet');
        $this->_writeToFile($block->toHtml());
    }
    
    /**
     * @TODO: Write to a different stylesheet depending on the store id
     *
     * @param string $string 
     * @return void
     * @author Nicholas Jones
     */
    protected function _writeToFile($string) {
        $file = Mage::getBaseDir() . "/skin/frontend/diy/default/css/autogenerated.css";
        
        if (file_exists($file) && is_writeable($file)) {
            $result = file_put_contents($file, $string, LOCK_EX);
            
            if ($result !== false) {
                return true;
            } else {
                throw new Exception("There was an unknown error writing to the file");
            }
        } else {
            throw new Exception("The stylesheet file is not writeable!");
        }
    }
}