<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<h1><?php echo $this->__('Shopping Cart') ?></h1>

<!-- CHECKOUT BUTTONS -->
<?php if(!$this->hasError()): ?>
    <ul class="checkout-types">
        <?php foreach ($this->getMethods('methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                <li><?php echo $methodHtml; ?></li>
                <?php break; // Only show one method at the top of the page ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
<!-- END CHECKOUT BUTTONS -->

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before') ?>

<!-- PRODUCTS IN CART -->
<form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post" id="cart-form">
    <fieldset>
        <?php $span_num = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
        <table id="cart" cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th rowspan="<?php echo $span_num ?>"><?php echo $this->__('Product Image') ?></th>
                    <th rowspan="<?php echo $span_num ?>"><?php echo $this->__('Product Name') ?></th>
                    <th colspan="<?php echo $span_num ?>"><?php echo $this->__('Unit Price') ?></th>
                    <th rowspan="<?php echo $span_num ?>"><?php echo $this->__('Qty') ?></th>
                    <th colspan="<?php echo $span_num ?>"><?php echo $this->__('Subtotal') ?></th>
                    <th rowspan="<?php echo $span_num ?>"><?php echo $this->__('Remove?') ?></th>
                </tr>
                <?php if ($span_num > 1): ?>
                    <tr>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                <?php endif ?>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="3">
                        <?php if($this->getContinueShoppingUrl()): ?>
                            <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><?php echo $this->__('Continue Shopping') ?></button>
                        <?php endif; ?>
                    </td>
                    <td colspan="3">
                        <button type="submit" title="<?php echo $this->__('Update Shopping Cart') ?>" class="button update"><?php echo $this->__('Update Shopping Cart') ?></button>
                    </td>
                </tr>
            </tfoot>
            <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
            </tbody>
        </table>
    </fieldset>
</form>
<!-- END PRODUCTS IN CART -->
        
<!-- CART COLUMNS -->
<div class="col2-set">
    <!-- COLUMN ONE -->
    <div class="col-1">
        <?php echo $this->getChildHtml('crosssell') ?>
    </div>
    <!-- END COL ONE -->

    <!-- COLUMN TWO -->
    <div class="col-2">
        <?php echo $this->getChildHtml('coupon') ?>
        <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
    </div>
    <!-- END COL TWO -->
</div>
<!-- END CART COLUMNS -->
<!-- TOTALS -->
<aside class="totals">
    <?php echo $this->getChildHtml('totals'); ?>
    <?php if(!$this->hasError()): ?>
        <ul class="checkout-types">
            <?php foreach ($this->getMethods('methods') as $method): ?>
                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                    <li><?php echo $methodHtml; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</aside>
<!-- END TOTALS -->
