<!-- SHOP NAVIGATION --> 
<nav> 
    <ul> 
        <li class="active"> 
            <a href="#">Furniture</a> 
            <ul> 
                <li> 
                    <a href="#">Living Room</a> 
                </li> 
                <li class="active"> 
                    <a href="#">Bedroom</a> 
                </li> 
            </ul> 
        </li> 
        <li> 
            <a href="#" class="level-top">Electronics</a> 
            <ul> 
                <li> 
                    <a href="#">Cell Phones</a> 
                </li> 
                <li> 
                    <a href="#">Cameras</a> 
                    <ul> 
                        <li> 
                            <a href="#">Accessories</a> 
                        </li> 
                        <li> 
                            <a href="#">Digital Cameras</a> 
                        </li> 
                    </ul> 
                </li> 
                <li> 
                    <a href="#">Computers</a> 
                    <ul> 
                        <li> 
                            <a href="#">Build Your Own</a> 
                        </li> 
                        <li> 
                            <a href="#">Laptops</a> 
                        </li> 
                        <li> 
                            <a href="#">Hard Drives</a> 
                        </li> 
                        <li> 
                            <a href="#">Monitors</a> 
                        </li> 
                        <li> 
                            <a href="#">RAM / Memory</a> 
                        </li> 
                        <li> 
                            <a href="#">Cases</a> 
                        </li> 
                        <li> 
                            <a href="#">Processors</a> 
                        </li> 
                        <li> 
                            <a href="#">Peripherals</a> 
                        </li> 
                    </ul> 
                </li> 
            </ul> 
        </li> 
        <li> 
            <a href="#">Apparel</a> 
            <ul> 
                <li> 
                    <a href="#">Shirts</a> 
                </li> 
                <li> 
                    <a href="#">Shoes</a> 
                    <ul> 
                        <li> 
                            <a href="#">Mens</a> 
                        </li> 
                        <li> 
                            <a href="#">Womens</a> 
                        </li> 
                    </ul> 
                </li> 
                <li> 
                    <a href="#">Hoodies</a> 
                </li> 
            </ul> 
        </li> 
        <li> 
            <a href="#">Music</a> 
        </li> 
        <li> 
            <a href="#">Ebooks</a> 
        </li> 
    </ul> 
</nav> 
<!-- END SHOP NAVIGATION -->