<!-- SITE NAVIGATION --> 
<ul class="site-navigation"> 
    <li> 
        <a href="<?php echo $this->getUrl("customer/account") ?>" title="My Account">My Account</a> 
    </li> 
    <li> 
        <a href="<?php echo $this->getUrl("wishlist") ?>" title="My Wishlist" class="top-link-wishlist">My Wishlist</a> 
    </li> 
    <li> 
        <a href="<?php echo $this->getUrl("checkout") ?>" title="Checkout" class="top-link-checkout">Checkout</a> 
    </li> 
    <li> 
        <a href="<?php echo $this->getUrl("customer/account/login") ?>" title="Log Out">Log Out</a> 
    </li> 
</ul> 
<!-- END SITE NAVIGATION -->