<!-- PRODUCT PAGINATION -->
<?php if($this->getLastPageNum()>1): ?>
<li class="pagination"> 
    <strong><?php echo $this->__('Page:') ?></strong>
    <ol>
    <?php if (!$this->isFirstPage()): ?>
        <li>
            <a class="previous" href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo $this->__('Previous') ?>">
                <?php if(!$this->getAnchorTextForPrevious()): ?>
                    <img src="<?php echo $this->getSkinUrl('images/icon-arrow-left.gif') ?>" alt="<?php echo $this->__('Previous') ?>" />
                <?php else: ?>
                    <?php echo $this->getAnchorTextForPrevious() ?>
                <?php endif;?>
            </a>
        </li>
    <?php endif;?>
    
    <?php if ($this->canShowFirst()): ?>
        <li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
    <?php endif;?>
    
    <?php if ($this->canShowPreviousJump()): ?>
        <li><a class="previous_jump" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
    <?php endif;?>
    
    <?php foreach ($this->getFramePages() as $_page): ?>
        <?php if ($this->isPageCurrent($_page)): ?>
            <li class="current"><?php echo $_page ?></li>
        <?php else: ?>
            <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
        <?php endif;?>
    <?php endforeach;?>
    
    <?php if ($this->canShowNextJump()): ?>
        <li><a class="next_jump" title="" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
    <?php endif;?>

    <?php if ($this->canShowLast()): ?>
      <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
    <?php endif;?>
    
    <?php if (!$this->isLastPage()): ?>
        <li>
            <a class="next" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo $this->__('Next') ?>">
                <?php if(!$this->getAnchorTextForNext()): ?>
                    <img src="<?php echo $this->getSkinUrl('images/icon-arrow-right.gif') ?>" alt="<?php echo $this->__('Next') ?>" />
                <?php else: ?>
                    <?php echo $this->getAnchorTextForNext() ?>
                <?php endif;?>
            </a>
        </li>
    <?php endif;?>
    </ol>
</li>
<?php endif;?>